### General Settings ###

splash_activity_class_name=SplashScreenActivitySecret
home_activity_class_name=BottomNavigation

support_email=support.secretcodes@jedyapps.com

# possible values: 0 = None, 1 = Interstitial, 2 = Offer+Interstitial, 3 = Offer
app_launch_rout_mode=2
postpone_launch_rout_sessions=0

display_offer_on_resume=3

# possible values: true, false
offer_page_new_installers_only=false

onetime_start_session=5

show_on_resume=true
always_show_try_limited_version_button=false

# possible values: -1 (disabled), 0 (all the time), 1 (minute) or more minutes
interstitial_capping=40

# possible values: true, false
interstitial_launch_ready_only=false

### AdManager Settings ###

# possible values: admob
ad_provider=admob

ad_unit_banner=ca-app-pub-3940256099942544/6300978111
ad_unit_interstitial=ca-app-pub-3940256099942544/1033173712
ad_unit_rewarded=ca-app-pub-3940256099942544/5224354917
ad_unit_native=ca-app-pub-3940256099942544/2247696110

### In App Purchases Settings ###

default_sku=sc_weekly_3d_trail_005_v1
onetime_default_sku=com.removeads.secretcodes
full_price_sku=full_price

revenue_cat_google_play_public_key=goog_njEpxDhsGtWkVGqAAKIcVTLqgwK

### AnalyticsManager Settings ###

# possible values: google,singular
# use comma as a delimiter, e.g.: analytics_providers=google,singular
analytics_providers=google,singular

privacy_policy_url=https://www.jedyapps.com/?page_id=1550
terms_conditions_url=https://www.jedyapps.com/?page_id=1555

### Rate Us ###

# possible values: 1 (in app rating), 2 (rate us filter)
display_rateus_mode=2
display_rateus_session_start=4

### Ext Dialog (native ad) ###
# possible values: 0 (disabled), 1 (banner), 2 (rate us - custom in-app review)
exit_dialog_mode=1
exit_dialog_ad_unit=ca-app-pub-8519912990016124/9465854763

### Happy Moment ###

# possible values: 0 (rate_us+interstitial), 1 (interstitial), rate_us (2)
happy_moment_mode=2
happy_moment_capping=2

# disable progress bar for splash screen
# possible values: true/false
splash_progress_bar_disabled=true